name: Workflow1

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs: 
      workflow2_name:
        description: 'Workflow2 Name for Triggering'
        required: true
        default: 'Workflow2'
      
      workflow2_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: 'manu6300'
      
      workflow2_repo_github:
        description: 'GitHub Repository Name'
        required: true
        default: 'githuaction'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: Build Image of
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: step
      run: |
        version=${GITHUB_REF##*/}-${GITHUB_SHA::7}
        echo -e "$version"
