name: src-workflow

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: Build Image of
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: step
      run: |
        version=${GITHUB_REF##*/}-${GITHUB_SHA::7}
        echo -e "$version"
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.MY_SRC_PAT }}
        repository: manu6300/githuaction
        event-type: my-event
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
